# 依存関係の禁止リスト
[bans]
# 複数バージョンを許可
multiple-versions = "allow"

# ライセンスポリシー
[licenses]
# 一般的なオープンソースライセンスを許可
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unlicense",
    "0BSD",
    "MPL-2.0",
    "Unicode-3.0",
    "CDLA-Permissive-2.0"
]

# 依存関係のソースポリシー
[sources]
# 許可するレジストリ
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# セキュリティアドバイザリの設定
[advisories]
# 脆弱性データベースのURL
db-urls = ["https://github.com/rustsec/advisory-db"]

# 特定のアドバイザリを無視
[[advisories.ignore]]
# pasteクレートは非推奨だが、metal依存関係のために一時的に無視
# metalチームが代替手段に移行するまで待機
id = "RUSTSEC-2024-0436"
reason = "Temporary ignore: paste unmaintained but required by metal crate"
