#!/bin/bash
# CI/CD Performance Regression Check Script
# Automatically generated by RusTorch Performance Regression Detector

set -e

echo "🔍 Running performance regression check..."

# Run benchmark and capture results
cargo run --example performance_regression_detector --features "metal coreml" --release > regression_results.log 2>&1

# Check for critical alerts
if grep -q "🚨\|🔴" regression_results.log; then
    echo "❌ CRITICAL PERFORMANCE REGRESSION DETECTED!"
    echo "📋 Alert Summary:"
    grep -E "🚨|🔴" regression_results.log
    echo ""
    echo "🔧 Recommended Actions:"
    echo "  1. Review recent changes"
    echo "  2. Check system resources"
    echo "  3. Consider rolling back"
    echo ""
    exit 1
elif grep -q "🟡" regression_results.log; then
    echo "⚠️  Performance warnings detected - monitoring required"
    grep "🟡" regression_results.log
    exit 0
else
    echo "✅ No performance regressions detected"
    exit 0
fi
