name: rustorch
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab>=3.0
  - matplotlib
  - pandas
  - numpy
  - rust
  - cargo
  - cmake
  - pkg-config
  - gcc_linux-64
  - gxx_linux-64
  - pip:
    - maturin>=1.0
    - wheel